---
development:
  cloud_name: drbiqekyx
  api_key: '762396651527585'
  api_secret: "-X3mGF-pRJ_6fbrUnwFIErcyoJQ"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drbiqekyx
  api_key: '762396651527585'
  api_secret: "-X3mGF-pRJ_6fbrUnwFIErcyoJQ"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drbiqekyx
  api_key: '762396651527585'
  api_secret: "-X3mGF-pRJ_6fbrUnwFIErcyoJQ"
  enhance_image_tag: true
  static_image_support: false
